from ubuntu:24.04

# Copying in the target program source code
RUN mkdir /target
COPY js.c /target

# TODO: Complete this Dockerfile.
# Carry out all necessary steps to apply and demonstrate
# the efficacy of your patch.
